hash-format = "sha256"

[[files]]
file = "index,html"
hash = "f2251190601777354f564eb26a5413b45cd817bf6598ccf37b4cb316bd6a6349"

[[files]]
file = "mods/audioplayer.pw.toml"
hash = "5f2f0ac0042cf3a274098074d3acee7e61692d1c0a2ef87d883f9607aeefef9d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/configured-defaults.pw.toml"
hash = "cb07f1e3b039be7c3e0e2fe4ad8289e9e800c66a4c4f4e5eb244d1a26dd542d3"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "f89f5f135170f999c531451c50937db67abeb0b0ff623d030f35f509837209a4"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "c668eaac99364f5f0fc467202d0fddfbd6a2126ea9c7b699f7ea86444e0b1269"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7adc0d54f139075d8f90dae18ca476753cc3145a70e09c9327736024adfe9b30"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "b7d33095f206cb34dc8cd3d5410a00597439a2fc793f4c158c7a2ecfc7e85e82"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c66e4b3576440113259b5bae8d0660b8e0023ce852156f27383f8651ecc4bfe3"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9ff1a261860fcb16a7c7f124d738abcdfc1297363412d237540685003ff04d6b"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "19f9479c1a4b9e5dee34eab19bcb54944a2044f69e58408fb85e7d1d5ce333dd"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "022c64cbff3fbce3b4a988405c6cb492a46592c83e842752331844de68c1d8c0"
metafile = true

[[files]]
file = "resourcepacks/DefaultPBR.zip"
hash = "505d06717d13742dfac4986de0a0e900b8cf56511807d6792d41ff8ba2df7f1a"

[[files]]
file = "resourcepacks/barebones.pw.toml"
hash = "8256b3484b0af222f968ef9b5570d9a8fb769880140b65edbeabff35906d54d8"
metafile = true

[[files]]
file = "shaderpacks/complementary_.reworked.pw.toml"
hash = "93a93c76a29aaa462a791ffeb6de48a2bb724dc68126c2b25d5fc3704b512a5d"
metafile = true

[[files]]
file = "shaderpacks/monophonic.pw.toml"
hash = "a23da57bb98fcebc6671e31667517e1c6fdadf3043f27bed09ff7b1b94b37fff"
metafile = true

[[files]]
file = "shaderpacks/sildurs_enhanced_default.pw.toml"
hash = "a860548c2b3d5cd63207f4159253aa4d6adee0c718d9fddac49ac3ef217566e1"
metafile = true
